# Generated by Django 3.0.4 on 2022-03-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='gorup',
            new_name='group',
        ),
    ]
