# Generated by Django 3.0.4 on 2022-03-08 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frend',
            new_name='Friend',
        ),
    ]
